# Generated BUILD file for src/com/bluegosling/collections/immutable
java_library(name='immutable',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/collections',
      'src/com/bluegosling/vars',
      'src/com/bluegosling/collections/maps',
      '3rdparty:guava',
      '3rdparty:jsr305'])