# Generated BUILD file for src/com/bluegosling/collections/immutable
java_library(name='immutable',
  sources=globs('*.java'),
  dependencies=['3rdparty:guava',
      '3rdparty:jsr305',
      'src/com/bluegosling/collections',
      'src/com/bluegosling/collections/maps',
      'src/com/bluegosling/vars'])
