# Generated BUILD file for test/com/bluegosling/concurrent/executors
java_tests(name='executors',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/concurrent/executors',
      'src/com/bluegosling/concurrent',
      'src/com/bluegosling/vars',
      'src/com/bluegosling/concurrent/fluent',
      '3rdparty:junit'])