# Generated BUILD file for test/com/bluegosling/concurrent/executors
java_tests(name='executors',
  sources=globs('*.java'),
  dependencies=['3rdparty:junit',
      'src/com/bluegosling/concurrent',
      'src/com/bluegosling/concurrent/executors',
      'src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/vars'])
