# Generated BUILD file for test/com/bluegosling/collections/tries
java_tests(name='tries',
  sources=globs('*.java'),
  dependencies=['3rdparty:commons-collections-testframework',
      '3rdparty:junit',
      'src/com/bluegosling/collections',
      'src/com/bluegosling/collections/tries',
      'src/com/bluegosling/testing',
      'test/com/bluegosling/testing'])
