# Generated BUILD file for src/com/bluegosling/concurrent/executors
java_library(name='executors',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/concurrent',
      'src/com/bluegosling/concurrent/contended',
      'src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/concurrent/futures',
      'src/com/bluegosling/collections',
      'src/com/bluegosling/tuples',
      'src/com/bluegosling/choice',
      'src/com/bluegosling/function',
      'src/com/bluegosling/collections/concurrent',
      'src/com/bluegosling/collections/queues'])