# Generated BUILD file for src/com/bluegosling/apt/testing
java_library(name='testing',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/collections',
      'src/com/bluegosling/reflect/caster',
      'src/com/bluegosling/reflect',
      '3rdparty:guava',
      '3rdparty:jsr305',
      '3rdparty:junit'])