# Generated BUILD file for src/com/bluegosling/generator
java_library(name='generator',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/concurrent',
      'src/com/bluegosling/vars'])
