# Generated BUILD file for test/com/bluegosling/possible
java_tests(name='possible',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/function',
      'src/com/bluegosling/testing',
      'src/com/bluegosling/possible',
      'src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/concurrent',
      'src/com/bluegosling/concurrent/extras',
      '3rdparty:junit'])