# Generated BUILD file for src/com/bluegosling/collections/queues
java_library(name='queues',
  sources=globs('*.java'),
  dependencies=['3rdparty:guava',
      '3rdparty:jsr305',
      'src/com/bluegosling/collections'])
