# Generated BUILD file for test/com/bluegosling/choice
java_tests(name='choice',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/possible',
      'src/com/bluegosling/vars',
      'src/com/bluegosling/testing',
      'src/com/bluegosling/choice',
      '3rdparty:junit'])