# Generated BUILD file for test/com/bluegosling/choice
java_tests(name='choice',
  sources=globs('*.java'),
  dependencies=['3rdparty:junit',
      'src/com/bluegosling/choice',
      'src/com/bluegosling/possible',
      'src/com/bluegosling/testing',
      'src/com/bluegosling/vars'])
