# Generated BUILD file for src/com/bluegosling/collections/maps
java_library(name='maps',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/collections',
      'src/com/bluegosling/collections/sets'])