language: java

jdk: [ oraclejdk8 ]


addons:
  apt:
    packages: [ oracle-java8-installer ]

script: "./pants --config-override=pants.travis-ci.ini test ::"

# Enables support for a docker container-based build
# which should provide faster startup times and beefier
# "machines". This is also required in order to use the
# cache configured below.
sudo: false

before_cache:
  # The `ivydata-*.properties` & root level `*.{properties,xml}` files'
  # effect on resolution time is in the noise, but they are
  # re-timestamped in internal comments and fields on each run and this
  # leads to travis-ci cache thrash.  Kill these files before the cache
  # check to avoid un-needed cache re-packing and re-upload (a ~100s
  # operation).
  - find $HOME/.ivy2/pants -type f -name "ivydata-*.properties" -print -delete
  - rm -fv $HOME/.ivy2/pants/*.{css,properties,xml,xsl}
  # The stats cache contains timestamped reports unused by CI but that
  # thrash the cache.  Skip caching these.
  - rm -rf $HOME/.cache/pants/stats

cache:
  directories:
    - $HOME/.cache/pants
    - $HOME/.ivy2/pants
    # TODO(John Sirois): Update this to ~/.npm/pants when pants starts
    # using its own isolated cache:
    #   https://github.com/pantsbuild/pants/issues/2485
    - $HOME/.npm

