#!/bin/bash
set -e
if [[ "$#" -eq 1 && "$1" == "--setup" ]]; then
  cd $(dirname $0)/.git/hooks
  ln -sfn ../../post-commit
  echo "post-commit hook configured"
  exit 0
elif [[ "$#" -ne 0 ]]; then
  echo "Expected no arguments"
  exit 1
fi

if git diff --name-only --diff-filter=ACM HEAD HEAD~1 \
    | grep '^README.md$'; then
  echo -e '---\nlayout: index\n---\n\n' > docs/index.md
  cat README.md >> docs/index.md
  git add docs/index.md >/dev/null
  git commit -am "sync README.md to docs/index.md" >/dev/null
  echo "Synchronized docs/index.md with README.md"
fi
