# Generated BUILD file for test/com/bluegosling/concurrent/atoms
java_tests(name='atoms',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/testing',
      'src/com/bluegosling/tuples',
      'src/com/bluegosling/concurrent/atoms',
      'src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/possible',
      'src/com/bluegosling/collections/maps',
      '3rdparty:junit'])