# Generated BUILD file for test/com/bluegosling/collections/queues
java_tests(name='queues',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/collections/queues',
      'test/com/bluegosling/collections',
      'test/com/bluegosling/testing',
      '3rdparty:junit'])