# Generated BUILD file for src/com/bluegosling/reflect
java_library(name='reflect',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/collections',
      'src/com/bluegosling/collections/maps',
      'src/com/bluegosling/function',
      'src/com/bluegosling/collections/primitive',
      'src/com/bluegosling/vars',
      '3rdparty:guava',
      '3rdparty:jsr305'])