# Generated BUILD file for test/com/bluegosling/concurrent/locks
java_tests(name='locks',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/testing',
      'src/com/bluegosling/vars',
      'src/com/bluegosling/concurrent/locks',
      'src/com/bluegosling/concurrent',
      '3rdparty:junit'])