# Generated BUILD file for test/com/bluegosling/concurrent/locks
java_tests(name='locks',
  sources=globs('*.java'),
  dependencies=['3rdparty:junit',
      'src/com/bluegosling/concurrent',
      'src/com/bluegosling/concurrent/locks',
      'src/com/bluegosling/testing',
      'src/com/bluegosling/vars'])
