# Generated BUILD file for test/com/bluegosling/processors
java_tests(name='processors',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/apt/testing',
      'src/com/bluegosling/processors',
      '3rdparty:junit'])