# Generated BUILD file for test/com/bluegosling/graph
java_tests(name='graph',
  sources=globs('*.java'),
  dependencies=['3rdparty:junit',
      'src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/graph',
      'src/com/bluegosling/testing'])
