# Generated BUILD file for test/com/bluegosling/graph
java_tests(name='graph',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/testing',
      'src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/graph',
      '3rdparty:junit'])