# Generated BUILD file for test/com/bluegosling/collections/primitive
java_tests(name='primitive',
  sources=globs('*.java'),
  dependencies=['test/com/bluegosling/collections',
      'src/com/bluegosling/collections/primitive',
      'test/com/bluegosling/testing',
      '3rdparty:junit'])