# Generated BUILD file for test/com/bluegosling/collections/primitive
java_tests(name='primitive',
  sources=globs('*.java'),
  dependencies=['3rdparty:junit',
      'src/com/bluegosling/collections/primitive',
      'test/com/bluegosling/collections',
      'test/com/bluegosling/testing'])
