# Generated BUILD file for test/com/bluegosling/testing
java_tests(name='testing',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/function',
      'src/com/bluegosling/testing',
      'src/com/bluegosling/reflect',
      '3rdparty:commons-collections-testframework',
      '3rdparty:junit'])