# Generated BUILD file for test/com/bluegosling/collections/immutable
java_tests(name='immutable',
  sources=globs('*.java'),
  dependencies=['3rdparty:commons-collections-testframework',
      '3rdparty:guava',
      '3rdparty:jsr305',
      '3rdparty:junit',
      'src/com/bluegosling/collections',
      'src/com/bluegosling/collections/immutable',
      'test/com/bluegosling/collections',
      'test/com/bluegosling/testing'])
