# Generated BUILD file for test/com/bluegosling/collections/immutable
java_tests(name='immutable',
  sources=globs('*.java'),
  dependencies=['test/com/bluegosling/testing',
      'test/com/bluegosling/collections',
      'src/com/bluegosling/collections',
      'src/com/bluegosling/collections/immutable',
      '3rdparty:commons-collections-testframework',
      '3rdparty:junit',
      '3rdparty:guava',
      '3rdparty:jsr305'])