# Generated BUILD file for src/com/bluegosling/reflect/model
java_library(name='model',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/reflect',
      'src/com/bluegosling/reflect/scanner',
      'src/com/bluegosling/util'])
