# Generated BUILD file for src/com/bluegosling/collections
java_library(name='collections',
  sources=globs('*.java'),
  dependencies=['3rdparty:guava',
      '3rdparty:jsr305',
      'src/com/bluegosling/function'])
