# Generated BUILD file for src/com/bluegosling/collections/lists
java_library(name='lists',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/collections',
      'src/com/bluegosling/tuples'])
