# Generated BUILD file for src/com/bluegosling/collections/tries
java_library(name='tries',
  sources=globs('*.java'),
  dependencies=['3rdparty:guava',
      '3rdparty:jsr305',
      'src/com/bluegosling/collections',
      'src/com/bluegosling/collections/bits',
      'src/com/bluegosling/collections/maps',
      'src/com/bluegosling/collections/primitive',
      'src/com/bluegosling/possible',
      'src/com/bluegosling/tuples'])
