# Generated BUILD file for src/com/bluegosling/collections/tables
java_library(name='tables',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/collections',
      '3rdparty:guava',
      '3rdparty:jsr305'])