# Generated BUILD file for src/com/bluegosling/derivations
java_library(name='derivations',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/reflect',
      'src/com/bluegosling/util'])
