# Generated BUILD file for src/com/bluegosling/concurrent
java_library(name='concurrent',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/util',
      'src/com/bluegosling/time',
      '3rdparty:guava',
      '3rdparty:jsr305'])