# Generated BUILD file for src/com/bluegosling/concurrent
java_library(name='concurrent',
  sources=globs('*.java'),
  dependencies=['3rdparty:guava',
      '3rdparty:jsr305',
      'src/com/bluegosling/util'])
