# Generated BUILD file for test/com/bluegosling/apt/testing
java_tests(name='testing',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/collections',
      'src/com/bluegosling/apt/testing',
      'src/com/bluegosling/vars',
      '3rdparty:junit'])