# Generated BUILD file for src/com/bluegosling/concurrent/atoms
java_library(name='atoms',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/concurrent',
      'src/com/bluegosling/concurrent/executors',
      'src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/function',
      'src/com/bluegosling/concurrent/locks',
      'src/com/bluegosling/tuples'])