# Generated BUILD file for src/com/bluegosling/reflect/blaster
java_library(name='blaster',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/reflect',
      '3rdparty:guava',
      '3rdparty:jsr305'])