# Generated BUILD file for test/com/bluegosling/collections/sorting
java_tests(name='sorting',
  sources=globs('*.java'),
  dependencies=['3rdparty:junit',
      'src/com/bluegosling/collections/sorting',
      'src/com/bluegosling/time'])
