# Generated BUILD file for test/com/bluegosling/collections/sorting
java_tests(name='sorting',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/collections/sorting',
      'src/com/bluegosling/time',
      '3rdparty:junit'])