# Generated BUILD file for src/com/bluegosling/choice
java_library(name='choice',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/possible',
      'src/com/bluegosling/util',
      'src/com/bluegosling/concurrent/fluent'])