# Generated BUILD file for src/com/bluegosling/apt/reflect
java_library(name='reflect',
  sources=globs('*.java'),
  dependencies=['3rdparty:guava',
      '3rdparty:jsr305',
      'src/com/bluegosling/apt',
      'src/com/bluegosling/collections',
      'src/com/bluegosling/reflect',
      'src/com/bluegosling/tuples'])
