# Generated BUILD file for test/com/bluegosling/concurrent
java_tests(name='concurrent',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/concurrent',
      'src/com/bluegosling/time',
      '3rdparty:junit'])