# Generated BUILD file for test/com/bluegosling/concurrent
java_tests(name='concurrent',
  sources=globs('*.java'),
  dependencies=['3rdparty:guava',
      '3rdparty:jsr305',
      '3rdparty:junit',
      'src/com/bluegosling/concurrent',
      'src/com/bluegosling/testing'])
