# Generated BUILD file for test/com/bluegosling/collections/maps
java_tests(name='maps',
  sources=globs('*.java'),
  dependencies=['3rdparty:commons-collections-testframework',
      '3rdparty:junit',
      'src/com/bluegosling/collections/maps',
      'test/com/bluegosling/collections',
      'test/com/bluegosling/testing'])
