# Generated BUILD file for test/com/bluegosling/collections
java_tests(name='collections',
  sources=globs('*.java'),
  dependencies=['3rdparty:commons-collections-testframework',
      '3rdparty:guava',
      '3rdparty:jsr305',
      '3rdparty:junit',
      'src/com/bluegosling/collections',
      'src/com/bluegosling/collections/bits',
      'src/com/bluegosling/collections/primitive',
      'src/com/bluegosling/function',
      'src/com/bluegosling/reflect',
      'src/com/bluegosling/testing',
      'test/com/bluegosling/testing'])
