# Generated BUILD file for src/com/bluegosling/concurrent/fluent
java_library(name='fluent',
  sources=globs('*.java'),
  dependencies=['3rdparty:guava',
      '3rdparty:jsr305',
      'src/com/bluegosling/collections',
      'src/com/bluegosling/concurrent',
      'src/com/bluegosling/concurrent/futures',
      'src/com/bluegosling/function',
      'src/com/bluegosling/tuples',
      'src/com/bluegosling/vars'])
