# Generated BUILD file for test/com/bluegosling/collections/lists
java_tests(name='lists',
  sources=globs('*.java'),
  dependencies=['test/com/bluegosling/collections',
      'src/com/bluegosling/collections/lists',
      'test/com/bluegosling/testing',
      '3rdparty:commons-collections-testframework',
      '3rdparty:junit'])