# Generated BUILD file for test/com/bluegosling/collections/lists
java_tests(name='lists',
  sources=globs('*.java'),
  dependencies=['3rdparty:commons-collections-testframework',
      '3rdparty:junit',
      'src/com/bluegosling/collections/lists',
      'test/com/bluegosling/collections',
      'test/com/bluegosling/testing'])
