# Generated BUILD file for src/com/bluegosling/streams
java_library(name='streams',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/collections',
      'src/com/bluegosling/function',
      'src/com/bluegosling/tuples',
      'src/com/bluegosling/choice',
      'src/com/bluegosling/vars',
      '3rdparty:guava',
      '3rdparty:jsr305'])