# Generated BUILD file for src/com/bluegosling/concurrent/scheduler
java_library(name='scheduler',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/concurrent',
      'src/com/bluegosling/collections'])