# Generated BUILD file for test/com/bluegosling/concurrent/scheduler
java_tests(name='scheduler',
  sources=globs('*.java'),
  dependencies=['3rdparty:junit',
      'src/com/bluegosling/concurrent/scheduler',
      'src/com/bluegosling/util',
      'test/com/bluegosling/concurrent/fluent'])
