# Generated BUILD file for test/com/bluegosling/concurrent/scheduler
java_tests(name='scheduler',
  sources=globs('*.java'),
  dependencies=['test/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/time',
      'src/com/bluegosling/concurrent/scheduler',
      '3rdparty:junit'])