# Generated BUILD file for src/com/bluegosling/reflect/scanner
java_library(name='scanner',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/concurrent',
      'src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/time'])