# Generated BUILD file for src/com/bluegosling/reflect/scanner
java_library(name='scanner',
  sources=globs('*.java'),
  dependencies=['3rdparty:guava',
      '3rdparty:jsr305',
      'src/com/bluegosling/concurrent',
      'src/com/bluegosling/concurrent/fluent'])
