# Generated BUILD file for src/com/bluegosling/collections/concurrent
java_library(name='concurrent',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/collections',
      'src/com/bluegosling/concurrent/locks',
      'src/com/bluegosling/collections/queues',
      'src/com/bluegosling/collections/sets',
      'src/com/bluegosling/concurrent/contended',
      'src/com/bluegosling/collections/immutable',
      'src/com/bluegosling/tuples',
      'src/com/bluegosling/vars'])