# Generated BUILD file for test/com/bluegosling/collections/concurrent
java_tests(name='concurrent',
  sources=globs('*.java'),
  dependencies=['test/com/bluegosling/collections',
      'src/com/bluegosling/collections',
      'src/com/bluegosling/collections/concurrent',
      'test/com/bluegosling/testing',
      'src/com/bluegosling/collections/immutable',
      '3rdparty:junit',
      '3rdparty:commons-collections-testframework'])