java_library(name='bluegosling',
             sources=rglobs('*.java'),
             dependencies=['3rdparty:javax.inject', '3rdparty:junit',
                           '3rdparty:guava', '3rdparty:jsr305',
                           '3rdparty:javaparser'])
