# Generated BUILD file for test/com/bluegosling/collections/sets
java_tests(name='sets',
  sources=globs('*.java'),
  dependencies=['3rdparty:junit',
      'src/com/bluegosling/collections/sets',
      'test/com/bluegosling/collections',
      'test/com/bluegosling/testing'])
