# Generated BUILD file for test/com/bluegosling/collections/sets
java_tests(name='sets',
  sources=globs('*.java'),
  dependencies=['test/com/bluegosling/collections',
      'src/com/bluegosling/collections/sets',
      'test/com/bluegosling/testing',
      '3rdparty:junit'])