# Generated BUILD file for src/com/bluegosling/concurrent/locks
java_library(name='locks',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/concurrent',
      'src/com/bluegosling/util'])
