# Generated BUILD file for test/com/bluegosling/reflect
java_tests(name='reflect',
  sources=globs('*.java'),
  dependencies=['3rdparty:guava',
      '3rdparty:jsr305',
      '3rdparty:junit',
      'src/com/bluegosling/collections/lists',
      'src/com/bluegosling/collections/maps',
      'src/com/bluegosling/reflect',
      'src/com/bluegosling/testing',
      'src/com/bluegosling/vars',
      'test/com/bluegosling/util/test'])
