# Generated BUILD file for src/com/bluegosling/testing
java_library(name='testing',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/reflect',
      'src/com/bluegosling/util',
      '3rdparty:junit'])