# Generated BUILD file for src/com/bluegosling/testing
java_library(name='testing',
  sources=globs('*.java'),
  dependencies=['3rdparty:junit',
      'src/com/bluegosling/reflect',
      'src/com/bluegosling/util'])
