# Generated BUILD file for src/com/bluegosling/concurrent/extras
java_library(name='extras',
  sources=globs('*.java'),
  dependencies=['3rdparty:guava',
      '3rdparty:jsr305',
      'src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/possible',
      'src/com/bluegosling/tuples',
      'src/com/bluegosling/util'])
