# Generated BUILD file for src/com/bluegosling/concurrent/extras
java_library(name='extras',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/possible',
      'src/com/bluegosling/util',
      'src/com/bluegosling/tuples',
      '3rdparty:guava',
      '3rdparty:jsr305'])