# Generated BUILD file for test/com/bluegosling/generator
java_tests(name='generator',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/testing',
      'src/com/bluegosling/concurrent',
      'src/com/bluegosling/generator',
      '3rdparty:junit'])