# Generated BUILD file for test/com/bluegosling/generator
java_tests(name='generator',
  sources=globs('*.java'),
  dependencies=['3rdparty:junit',
      'src/com/bluegosling/concurrent',
      'src/com/bluegosling/generator',
      'src/com/bluegosling/testing'])
