# Generated BUILD file for test/com/bluegosling/concurrent/fluent
java_tests(name='fluent',
  sources=globs('*.java'),
  dependencies=['3rdparty:junit',
      'src/com/bluegosling/concurrent',
      'src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/testing',
      'src/com/bluegosling/util'])
