# Generated BUILD file for test/com/bluegosling/concurrent/fluent
java_tests(name='fluent',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/concurrent',
      'src/com/bluegosling/testing',
      'src/com/bluegosling/time',
      '3rdparty:junit'])