# Generated BUILD file for src/com/bluegosling/graph
java_library(name='graph',
  sources=globs('*.java'),
  dependencies=['src/com/bluegosling/concurrent/fluent',
      'src/com/bluegosling/reflect',
      'src/com/bluegosling/result',
      'src/com/bluegosling/concurrent',
      '3rdparty:guava',
      '3rdparty:jsr305'])